//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindBarrierReinforcement.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindBarrierReinforcement.Resources.EN", typeof(EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis Offset.
        /// </summary>
        internal static string Lbl_AR_Ext_AxisOffset {
            get {
                return ResourceManager.GetString("Lbl_AR_Ext_AxisOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Offset.
        /// </summary>
        internal static string Lbl_AR_Ext_BottomOffset {
            get {
                return ResourceManager.GetString("Lbl_AR_Ext_BottomOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter For Larger U Bar.
        /// </summary>
        internal static string Lbl_AR_Ext_Diameter_Ularger {
            get {
                return ResourceManager.GetString("Lbl_AR_Ext_Diameter_Ularger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Offset.
        /// </summary>
        internal static string Lbl_AR_Ext_TopOffset {
            get {
                return ResourceManager.GetString("Lbl_AR_Ext_TopOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter values for.
        /// </summary>
        internal static string UBAB_Label_Title {
            get {
                return ResourceManager.GetString("UBAB_Label_Title", resourceCulture);
            }
        }
    }
}
