//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindBarrierReinforcement.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindBarrierReinforcement.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D10.
        /// </summary>
        internal static string EDiameters_D10 {
            get {
                return ResourceManager.GetString("EDiameters_D10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D12.
        /// </summary>
        internal static string EDiameters_D12 {
            get {
                return ResourceManager.GetString("EDiameters_D12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D14.
        /// </summary>
        internal static string EDiameters_D14 {
            get {
                return ResourceManager.GetString("EDiameters_D14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D16.
        /// </summary>
        internal static string EDiameters_D16 {
            get {
                return ResourceManager.GetString("EDiameters_D16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D18.
        /// </summary>
        internal static string EDiameters_D18 {
            get {
                return ResourceManager.GetString("EDiameters_D18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D20.
        /// </summary>
        internal static string EDiameters_D20 {
            get {
                return ResourceManager.GetString("EDiameters_D20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D25.
        /// </summary>
        internal static string EDiameters_D25 {
            get {
                return ResourceManager.GetString("EDiameters_D25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D32.
        /// </summary>
        internal static string EDiameters_D32 {
            get {
                return ResourceManager.GetString("EDiameters_D32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D40.
        /// </summary>
        internal static string EDiameters_D40 {
            get {
                return ResourceManager.GetString("EDiameters_D40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D6.
        /// </summary>
        internal static string EDiameters_D6 {
            get {
                return ResourceManager.GetString("EDiameters_D6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D8.
        /// </summary>
        internal static string EDiameters_D8 {
            get {
                return ResourceManager.GetString("EDiameters_D8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Of Bars.
        /// </summary>
        internal static string EOption_NoOfBars {
            get {
                return ResourceManager.GetString("EOption_NoOfBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Bars&amp;Length.
        /// </summary>
        internal static string EOption_NoOfBars_Length {
            get {
                return ResourceManager.GetString("EOption_NoOfBars_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Bars&amp;Spacing.
        /// </summary>
        internal static string EOption_NoOfBars_Spacing {
            get {
                return ResourceManager.GetString("EOption_NoOfBars_Spacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing.
        /// </summary>
        internal static string EOption_Spacing {
            get {
                return ResourceManager.GetString("EOption_Spacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing&amp;Length.
        /// </summary>
        internal static string EOption_Spacing_Length {
            get {
                return ResourceManager.GetString("EOption_Spacing_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        internal static string Page01 {
            get {
                return ResourceManager.GetString("Page01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor.
        /// </summary>
        internal static string Page02 {
            get {
                return ResourceManager.GetString("Page02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piles.
        /// </summary>
        internal static string Page03 {
            get {
                return ResourceManager.GetString("Page03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Reinforcement.
        /// </summary>
        internal static string Page04 {
            get {
                return ResourceManager.GetString("Page04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Reinforcement.
        /// </summary>
        internal static string Page05 {
            get {
                return ResourceManager.GetString("Page05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Plate Bottom Reinforcement.
        /// </summary>
        internal static string Page06 {
            get {
                return ResourceManager.GetString("Page06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Plate Top Reinforcement.
        /// </summary>
        internal static string Page07 {
            get {
                return ResourceManager.GetString("Page07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchors Reinforcement.
        /// </summary>
        internal static string Page08 {
            get {
                return ResourceManager.GetString("Page08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U Bars Around Bolts.
        /// </summary>
        internal static string Page09 {
            get {
                return ResourceManager.GetString("Page09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chairs.
        /// </summary>
        internal static string Page10 {
            get {
                return ResourceManager.GetString("Page10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        internal static string Page11 {
            get {
                return ResourceManager.GetString("Page11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BS8666.
        /// </summary>
        internal static string Page12 {
            get {
                return ResourceManager.GetString("Page12", resourceCulture);
            }
        }
    }
}
